Correctifs mars 2023
ansforge/FIG_ans-ig-mesures pull request #17
Opened 2023-03-01 13:29 UTC by nicolasArnoux

Peux merger cette version dans la MAIN?
La MAIN a 3 mois de retard.

2023-03-01 13:37 UTC, nriss approved these changes

2023-03-02 15:00 UTC, nriss requested changes
Top! quelques petits commentaires :)

2023-03-02 15:00 UTC, nriss commented on input/pagecontent/Liste-des-profils.page.md
>  Les profils FHIR pour les mesures de santé décrites dans ce document s'appuient sur la ressource standard Observation définie par HL7, en ajoutant quelques contraintes : Ces contraintes sont indiquée
": ces contraintes" sans majuscules
"détaillée" au lieu de "détaillé"

2023-03-02 15:00 UTC, nriss commented on input/fsh/MesFrObservationBodyWeight.fsh
>  * device ^short = "Dispositif utilisé pour l'observation"
A mon sens, il n'est pas nécessaire d'ajouter la mention "Non utilisé", le mieux étant d'utiliser le tag MS (MustSupport) pour indiquer les champs importants dans le cadre de cette spec

2023-03-02 15:00 UTC, nriss commented on input/fsh/MesObservationGlucose.fsh
> +* extension[MesMomentOfMeasurement].value[x] from $JDV-J157-MomentGlucose-MES (required)
Il vaut mieux rajouter les contraintes sur value[x] dans la définition de l'extension mes-moment-of-measurement

Le datatype doit être précisé également

2023-03-02 15:00 UTC, nriss commented on input/fsh/MesObservationWaistCircumference.fsh
>  * extension[MesReasonForMeasurement] ^definition = "Motif de la mesure\r\nTexte libre (ex. surpoids ou obésité, diabète, maladie du cœur et des vaisseaux, tabac…)"
Il y a encore ENS : ENS_ReasonForMeasurement

2023-03-02 15:00 UTC, nriss commented on input/fsh/MesObservationPainSeverity.fsh
> +* method ^binding.description = $JDV-J159-MethodPainSeverity-MES
Slicing de component à supprimer

2023-03-02 15:00 UTC, nriss commented on input/fsh/MesFrObservationHeartrate.fsh
>  * extension ^slicing.discriminator.type = #value
Définition des extensions avec contains et enlever les ^sliceName

2023-03-02 15:03 UTC, nicolasArnoux commented on dependency/NOS/DV_J15-ClasseAge-ROR-FHIR.json
> +{
Je ne comprends pas ce que ce JDV ROR fait dans le volet Mesures. Et ce n'est pas moi qui ai créé le répertoire Dependency.

2023-03-07 14:36 UTC, nicolasArnoux commented on input/fsh/Extensions/MesMomentOfMeasurement.fsh
> +* url = Canonical(mes-moment-of-measurement) (exactly)
URL supprimée dans les extensions

2023-03-07 14:38 UTC, nicolasArnoux commented on input/fsh/MesFrObservationBodyWeight.fsh
>  * device ^short = "Dispositif utilisé pour l'observation"
Cela avait été explicitement acté dans la spec initiale par la CNAM.

2023-03-07 14:43 UTC, nicolasArnoux commented on input/fsh/MesObservationGlucose.fsh
> +* extension[MesMomentOfMeasurement].value[x] from $JDV-J157-MomentGlucose-MES (required)
Corrigé: la description a été intégrée dans l'extension. Le binding sur JDV reste dans le profil car l'extension peut porter différents JDV

2023-03-09 15:54 UTC, sdemeyANS requested changes

2023-03-09 15:54 UTC, sdemeyANS commented on input/fsh/Extensions/MesNumberOfDays.fsh
>  * valueCodeableConcept.coding.system 1..
peut être que ces lignes sont à supprimer dans les extensions 
* valueCodeableConcept.coding ..1
* valueCodeableConcept.coding.system 1..
* valueCodeableConcept.coding.code 1..
peut être un résidu goFSH ?

2023-03-09 15:54 UTC, sdemeyANS commented on input/fsh/MesFrObservationBmi.fsh
>  * dataAbsentReason.coding.system 1..
ligne 16 et 17 peux-tu juste m'expliquer la cardinalité 1.. stp ?

2023-03-09 15:54 UTC, sdemeyANS commented on input/fsh/MesFrObservationBodyTemperature.fsh
>  * dataAbsentReason.coding.system 1..
idem peux-tu expliquer l'utilisation de la cardinalité 1.. stp ?

2023-03-09 15:54 UTC, sdemeyANS commented on input/fsh/MesFrObservationBodyTemperature.fsh
>  * dataAbsentReason.coding.code 1..
idem :)

2023-03-09 15:54 UTC, sdemeyANS commented on input/fsh/MesFrObservationBodyTemperature.fsh
>  * bodySite.coding.system 1..
idem lignes 34, 35, 39 et 40 :)

2023-03-09 15:54 UTC, sdemeyANS commented on input/fsh/MesFrObservationBodyWeight.fsh
>  * dataAbsentReason.coding.system 1..
idem sur la cardinalité lignes 28 et 29 :)

2023-03-09 15:54 UTC, sdemeyANS commented on input/fsh/MesFrObservationBodyWeight.fsh
>  * valueQuantity = http://unitsofmeasure.org#kg
idem cardinalté 23 et 24 :)

2023-03-09 15:54 UTC, sdemeyANS commented on input/fsh/MesFrObservationBp.fsh
>  * bodySite.coding.system 1..
idem concerant la cardinalité lignes 31 et 32 :)

2023-03-09 15:54 UTC, sdemeyANS commented on input/fsh/MesFrObservationBp.fsh
>  * method.coding.system 1..
idem cardinalité ligne 36 et 37 :)

2023-03-09 15:54 UTC, sdemeyANS commented on input/fsh/MesFrObservationBp.fsh
>  * referenceRange.appliesTo.coding.system 1..
idem cardinalité lignes 45 e t46 :)

2023-03-09 15:54 UTC, sdemeyANS commented on input/fsh/MesFrObservationBmi.fsh
Suggestion : peut être avoir un sous répertoire "profiles"

2023-03-09 15:54 UTC, sdemeyANS commented on input/fsh/MesFrObservationHeartrate.fsh
>  * extension[MesMomentOfMeasurement] ^definition = "Moment de la mesure\r\nTexte libre"
lignes 27 et 28 :)

2023-03-09 15:54 UTC, sdemeyANS commented on input/fsh/MesObservationGlucose.fsh
>  * valueQuantity.system 1..
lignes 54 et 56  :)

2023-03-09 15:54 UTC, sdemeyANS commented on input/fsh/MesObservationGlucose.fsh
> +* valueQuantity.code ^binding.description = $JDV-J163-GlucoseUnits-MES
lignes 60 et 61 même question sur la cardinalité :)

2023-03-09 15:54 UTC, sdemeyANS commented on input/fsh/MesObservationHeadCircumference.fsh
>  * valueQuantity.system 1..
même question sur la cardinalité :)

2023-03-09 15:54 UTC, sdemeyANS commented on input/fsh/MesObservationHeadCircumference.fsh
>  * valueQuantity.system 1..
a rediscuter dans tous les profils j'arrête d'ajouter des commentaires de ce type :)

2023-03-09 15:54 UTC, sdemeyANS commented on input/fsh/MesObservationStepsByDay.fsh
>  Parent: $vitalsigns
pourquoi ne pas partir de la ressource Observation?

2023-03-09 15:54 UTC, sdemeyANS commented on input/fsh/MesObservationHeadCircumference.fsh
>  Parent: $vitalsigns
pourquoi ne pas partir de la ressource Observation?

2023-03-10 09:51 UTC, nicolasArnoux commented on input/fsh/Extensions/MesDiabetisType.fsh
>  Id: mes-diabetis-type
Ajouté "Type de diabète" comme définition

2023-03-10 09:53 UTC, nicolasArnoux commented on input/fsh/Extensions/MesNumberOfDays.fsh
>  * valueCodeableConcept.coding ..1
Cette cardinalité a été définie par la CNAM dans la spec Word initiale de l'extension.

2023-03-10 10:01 UTC, nicolasArnoux commented on input/fsh/Extensions/MesNumberOfDays.fsh
>  * valueCodeableConcept.coding ..1
La spec word initiale définie par la CNAM spécifiait une cardinalité 0..1 pour valueCodeableConcept.
GoFSH a généré ces lignes qui impactent valueCodeableConcept.coding et pas directement valueCodeableConcept...
Je ne sais pas si on peut remplacer ces 3 lignes 
* valueCodeableConcept.coding ..1
* valueCodeableConcept.coding.system 1..
* valueCodeableConcept.coding.code 1..

par

* valueCodeableConcept ..1 ?

2023-03-10 10:02 UTC, nicolasArnoux commented on input/fsh/MesObservationStepsByDay.fsh
>  Parent: $vitalsigns
Cela a été décidé au niveau CNAM dès le départ. Ces observations sont des signes vitaux.

2023-03-10 10:03 UTC, nicolasArnoux commented on input/fsh/MesObservationHeadCircumference.fsh
>  Parent: $vitalsigns
Cela a été décidé au niveau CNAM dès le départ. Ces observations sont des signes vitaux.

2023-03-10 10:03 UTC, nicolasArnoux commented on input/pagecontent/NOTES.md
> +GHénéralités: enlever 1 ilgne au début
A supprimer. Des notes personnelles.

2023-03-10 10:04 UTC, nicolasArnoux commented on sushi-config.yaml
> +canonical: http://interop.esante.gouv.fr/ig/fhir/mesures
A voir avec Nicolas

2023-03-10 10:06 UTC, nicolasArnoux commented on input/fsh/Extensions/MesNumberOfDays.fsh
>  * valueCodeableConcept.coding.system 1..
C'est du GoFSH. A discuter s'il faut les supprimer ou mettre une cardinalité valueCodeableConcept ..1

2023-03-10 10:19 UTC, nriss commented on input/fsh/Extensions/MesNumberOfDays.fsh
>  * valueCodeableConcept.coding ..1
Ok pour moi!

2023-03-10 10:20 UTC, nriss commented on input/fsh/MesObservationStepsByDay.fsh
>  Parent: $vitalsigns
Pour moi c'est pas vraiment un signe vital les nombre de pas par jour, mais ok on va pas tout changer pour MES!

2023-03-10 10:20 UTC, nriss commented on sushi-config.yaml
> +canonical: http://interop.esante.gouv.fr/ig/fhir/mesures
Je confirme! L'url d'accès : https://interop.esante.gouv.fr/

2023-03-10 10:21 UTC, nriss commented on input/fsh/Extensions/MesNumberOfDays.fsh
>  * valueCodeableConcept.coding.system 1..
Ok pour remplacer :)

2023-03-10 10:25 UTC, sdemeyANS commented on input/fsh/Extensions/MesNumberOfDays.fsh
>  * valueCodeableConcept.coding.system 1..
@nriss qu'en penses-tu ?

2023-03-10 10:38 UTC, nriss commented on input/fsh/Extensions/MesNumberOfDays.fsh
>  * valueCodeableConcept.coding.system 1..
Ok pour mettre "valueCodeableConcept ..1" :)

2023-03-10 11:54 UTC, nicolasArnoux commented on input/fsh/Extensions/MesDiabetisType.fsh
>  * value[x] only CodeableConcept
Fait

2023-03-10 11:54 UTC, nicolasArnoux commented on input/fsh/Extensions/MesNumberOfDays.fsh
>  * valueCodeableConcept.coding ..1
Fait

2023-03-10 11:54 UTC, nicolasArnoux commented on input/fsh/Extensions/MesNumberOfDays.fsh
>  * valueCodeableConcept.coding.system 1..
Fait

2023-03-16 11:22 UTC, merged